### ISSUE TITLE
fail to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [ondrap/json-stream#23]
```
json-stream                    > /tmp/stack-f7d350cae3262115/json-stream-0.4.2.4/Data/JsonStream/Parser.hs:377:36: error:
json-stream                    >     • Couldn't match type: HMap.HashMap T.Text AE.Value
json-stream                    >                      with: Data.Aeson.KeyMap.KeyMap AE.Value
json-stream                    >       Expected: [(T.Text, AE.Value)] -> AE.Object
json-stream                    >         Actual: [(T.Text, AE.Value)] -> HMap.HashMap T.Text AE.Value
json-stream                    >     • In the second argument of ‘(.)’, namely ‘HMap.fromList’
json-stream                    >       In the first argument of ‘(<$>)’, namely
json-stream                    >         ‘AE.Object . HMap.fromList’
json-stream                    >       In the expression:
json-stream                    >         AE.Object . HMap.fromList
json-stream                    >           <$> callParse (manyReverse (objectItems aeValue)) tok
json-stream                    >     |
json-stream                    > 377 |         ObjectBegin -> AE.Object . HMap.fromList <$> callParse (manyReverse (objectItems aeValue)) tok
json-stream                    >     |                                    ^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
As a Hackage trustee, I have created revisions for v0.4.1.0 to v0.4.2.4 that add bounds `aeson < 1.6`. See e.g. https://hackage.haskell.org/package/json-stream-0.4.2.4/revisions/.
