### ISSUE TITLE
Fails to build with text-2.0

### ISSUE THREAD

**Issue by Bodigrim** [ondrap/json-stream#34]
```
$ cabal build --constraint 'text >= 2.0'
[3 of 5] Compiling Data.JsonStream.Unescape

Data/JsonStream/Unescape.hs:36:37: error:
    Not in scope: ‘A.maBA’
    Module ‘Data.Text.Array’ does not export ‘maBA’.
   |
36 |                 res <- c_js_decode (A.maBA dest) destOffPtr curPtr end
   |                                     ^^^^^^
```

**Comment by ondrap** [comment]
Well...yes. text-2.0 is in UTF-8 and json-stream is doing UTF-8 -> UTF-16 decoding in the background. This part would need to be rewritten.
